[mcp_servers.typocop-mcp]
args = ["-e",".env-typocop"]
command = "typocop-mcp"
enabled = false

[mcp_servers.typocop-mcp.tools.get_symbol_context]
approval_mode = "approve"

[mcp_servers.typocop-mcp.tools.impact_analysis]
approval_mode = "approve"
